### ISSUE TITLE
How do I save texture2D or  custom class

### ISSUE THREAD

**Issue by TheFlyingHawk** [nateonusapps/WebGLFileSaverForUnity#1]
SaveFile(string content
The incoming is a string object

**Comment by Nateonus** [comment]
You'll need to save your class or texture as a byte array.

Currently this isn't available, but I'm working on it and it should be done within the next week or so.

The following issue has more information regarding this.
https://github.com/Nateonus/WebGLFileSaverForUnity/issues/2
