### ISSUE TITLE
Saving a jpg file not working.

### ISSUE THREAD

**Issue by danielkotzer** [nateonusapps/WebGLFileSaverForUnity#2]
Hi,

I want to save a jpg file, here is my code:
    Texture2D texture = ScreenCapture.CaptureScreenshotAsTexture();
     byte[] textureBytes = texture.EncodeToJPG();
      string content = Convert.ToBase64String(textureBytes);
      WebGLFileSaver.SaveFile(content, ""+System.DateTime.Now.ToString("dd-MM-yyyy-HH-mm-ss") + ".jpg", "image/jpeg");
      Destroy(texture);

Can't open the file on Photoshop, the format is wrong. What did I do wrong?

**Comment by rohan-percept** [comment]
hey @danielkotzer ,
Did you figure this out?

**Comment by DrSharky** [comment]
Having the same issue, with almost identical code.
I even debugged the base64 string and used an online converter, the base64 string is correct on the Unity side.
There must be something wrong on the plugin side.
I edited the jslib to include a `console.log(Pointer_stringify(content))` line that prints the base64 string that the plugin receives. The output in the Google Chrome console works just fine. So the plugin is receiving the base64 string correctly.
Opening the "image" that the plugin downloads in a text editor, reveals that the file it saves is simply a text file with the base64 string inside.
So, maybe the MIME type isn't being properly converted in the plugin? I know I input the MIME type correctly, as the code above does.

**Comment by systemprintln** [comment]
Has anyone already found a solution? I tried .png but it isn't working either.

**Comment by lmaopaolo** [comment]
Any progress? I'm under the same assumption that the plugin is not performing the conversion correctly because the _"default is set to "text/plain;charset=utf-8" (a plain-text file)"_ is all that I am left with despite inputting the MIMEtype correctly (same code as above). Or maybe I'm not inputting it correctly? I'm going to tinker with it til then.

**Comment by danielkotzer** [comment]
Hi,
I found a solution that is working for me, in a folder called Plugins,
inside the Asset folder of my project I have a file
called: ImageDownloader.jslib

in contains this code:

var ImageDownloaderPlugin = {
  ImageDownloader: function(str, fn) {
      var msg = Pointer_stringify(str);
      var fname = Pointer_stringify(fn);
      var contentType = 'image/jpeg';
      function fixBinary (bin)
      {
        var length = bin.length;
        var buf = new ArrayBuffer(length);
        var arr = new Uint8Array(buf);
        for (var i = 0; i < length; i++)
        {
              arr[i] = bin.charCodeAt(i);
        }
        return buf;
      }
      var binary = fixBinary(atob(msg));
      var data = new Blob([binary], {type: contentType});
      var link = document.createElement('a');
    link.download = fname;
    link.innerHTML = 'DownloadFile';
    link.setAttribute('id', 'ImageDownloaderLink');
    if(window.webkitURL != null)
    {
        link.href = window.webkitURL.createObjectURL(data);
    }
    else
    {
        link.href = window.URL.createObjectURL(data);
        link.onclick = function()
        {
            var child = document.getElementById('ImageDownloaderLink');
            child.parentNode.removeChild(child);
        };
        link.style.display = 'none';
        document.body.appendChild(link);
    }
    link.click();
  }
};
mergeInto(LibraryManager.library, ImageDownloaderPlugin);


----------------------------------------------------------------------

on the button I click to save image I have this script attached:
using UnityEngine;
using UnityEngine.EventSystems;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System;

public class savePicture : MonoBehaviour, IPointerClickHandler
{
    public Camera RenderCamera;
    RenderTexture Rtexture;

    //
https://forum.unity.com/threads/user-image-download-from-in-webgl-app.474715/

    [DllImport("__Internal")]
    private static extern void ImageDownloader(string str, string fn);

    public static byte[] ssData = null;
    public static string imageFilename = "";



    // Start is called before the first frame update
    void Start()
    {

    }



    public void OnPointerClick(PointerEventData eventData)
    {
        StartCoroutine(takePicture());
    }


    Texture2D toTexture2D(RenderTexture rTex)
    {
        Texture2D tex = new Texture2D(rTex.width, rTex.height,
TextureFormat.RGB24, false);
        RenderTexture.active = rTex;
        tex.ReadPixels(new Rect(0, 0, rTex.width, rTex.height), 0, 0);
        tex.Apply();
        return tex;
    }

    IEnumerator takePicture()
    {
        //RenderCamera.backgroundColor = Color.white;
        //RenderCamera.backgroundColor = new Color32(196,238,255,255);

        if (RenderCamera.targetTexture != null)
        {
            RenderCamera.targetTexture.Release();
        }

        RenderCamera.targetTexture = new RenderTexture(2000, 1500, 24);

        Rtexture = RenderCamera.targetTexture;


        RenderCamera.enabled = true;

        yield return new WaitForEndOfFrame();

        Texture2D texture = toTexture2D(Rtexture);
        //Texture2D texture = ScreenCapture.CaptureScreenshotAsTexture();


        byte[] textureBytes = texture.EncodeToJPG(100);
        ImageDownloader(System.Convert.ToBase64String(textureBytes), "" +
System.DateTime.Now.ToString("dd-MM-yyyy-HH-mm-ss") + ".jpg");

        //string content = Convert.ToBase64String(textureBytes);
        //WebGLFileSaver.SaveFile(content,
""+System.DateTime.Now.ToString("dd-MM-yyyy-HH-mm-ss") + ".jpg",
"image/jpeg");

        //RenderCamera.backgroundColor = Color.black;

        Destroy(texture);

        if (RenderCamera.targetTexture != null)
        {
            RenderCamera.targetTexture.Release();
            RenderCamera.targetTexture = null;
            Rtexture = null;
        }
    }

}

----------------------------------------------

this is working for me, I use Unity 2019.4.16f1 (64-bit)

All the best

**Comment by nateonusapps** [comment]
Ah darn, this entire account was registered with a different email so not had any notifications about this.

I'll take a look into this as soon as I can - I once managed to get it working using Base64 and the encode to PNG Unity function. 

Really sorry for the delay guys!

**Comment by nateonusapps** [comment]
> Any progress? I'm under the same assumption that the plugin is not performing the conversion correctly because the _"default is set to "text/plain;charset=utf-8" (a plain-text file)"_ is all that I am left with despite inputting the MIMEtype correctly (same code as above). Or maybe I'm not inputting it correctly? I'm going to tinker with it til then.

I'm yet to test it, but this seems to be the problem. The blob is created as general text, when it should copy the MIME type of the file. 

I'll run a few tests and then let people know what happens.

**Comment by danielkotzer** [comment]
It is not working on the editor, only on the server when I upload the build
to my site. And I run it on Unity 2019.

בתאריך יום ב׳, 12 ביולי 2021, 15:31, מאת nateonusapps ‏<
***@***.***>:

**Comment by nateonusapps** [comment]
> It is not working on the editor, only on the server when I upload the build to my site. And I run it on Unity 2019.

The plugin can't work inside the editor I'm afraid, because it uses certain browser JavaScript functions.

If you want to save a file in the editor, then you'll need to use a local file save. I'd recommend using this plugin (https://github.com/gkngkc/UnityStandaloneFileBrowser) with the standard System.IO library functions.

**Comment by Nateonus** [comment]
Alright - The problem is actually due to trying to save a byte array as a string. The Pointer_Stringify function from emscripten is doing just that - Converting a pointer to a string. Unfortunately, images (and other data) are stored as byte arrays, not strings.

I don't have an environment where I can fix this just yet, but there exists a HEAPU8 thing, which should allow me to pass in an array of 8-bit unsigned integers - Identical to a byte array. 

https://forum.unity.com/threads/problems-saving-files-from-webgl-via-javascript-conversion-of-byte-array.759077/

The solution at the bottom of this page shows how to create a byte array in the JSLib file. I'l create a new function, so users will have to call SaveByteArray() or something like that. I'll be able to get this done in a few days hopefully, depends when TalkTalk gets my internet working properly. Thanks for the patience guys!

**Comment by kostasvs** [comment]
@Nateonus @danielkotzer @rohan-percept @DrSharky @systemprintln @lmaopaolo I submitted pull request #3 which should do just what you need - it allows passing a byte array as file content. Let me know if it helps!

**Comment by Nateonus** [comment]
Accepted pull request - Textures and byte arrays should now be supported.
